levels = [
  [ " g br   ",
    " gmbmrrr",
    " grmbbbb",
    " grbmbr ",
    " mgggggg",
    "        "],

  [ " br  g  ",
    " brrmgr ",
    " brrrmgG",
    " bmrrrm ",
    " mbbbmr ",
    " gggmbr ",
    "bbbmgbr ",
    "   B BR " ],
  [ "    gr  ",
    "bbb m m ",
    " mm  r R",
    " brmbrg ",
    "rrmg  m ",
    "ggggm m ",
    " mgggm R",
    "  G G B "],
  [ "    r   ",
    "bbb m m ",
    " bm  b B",
    "bbb  b B",
    "bbmr rm ",
    "rrrrmbm ",
    "r rmrbb ",
    "  RRR B "],
  [ "    br    ",
    "bbbbm mm B",
    "gggmbr br ",
    "rrr  rmmr ",
    " rm  rrrrR",
    "gg gm  bbB",
    "rrmgg rbm ",
    "   ggrr   "]
];
